language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-27.0.3
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - "chmod +x gradlew"

script:
  - ./gradlew ktlint
  - ./gradlew build
